const fs = require('fs');
const path = require('path');

function parse() {
  // 1. Parse the PEG description
  // 2. Match the PEG against source input
  return 1;
}

function compile(source, flags) {
  // 3. Parse the tree generated by the above matching
  // 4. Traverse the parse tree and emit code
}

function compileFile(file, flags) {
  const arch = require(path.resolve(path.join("arch", flags.arch)));
  const code = arch(file);
  code.emitInt();
  code.emitModule();
}

module.exports = {
  parse,
  compile,
  compileFile,
};
