const fs = require('fs');
const path = require('path');
const peg = require('./peg');

function parse(input) {
  // 1. Parse the PEG description
  const grammar = fs.readFileSync(path.resolve('lang.peg')).toString();
  // 2. Match the PEG against source input
  return peg.pegc(grammar).match(input);
}

function compile(source, flags) {
  // 3. Parse the tree generated by the above matching
  // 4. Traverse the parse tree and emit code
}

function compileFile(file, flags) {
  const arch = require(path.resolve(path.join("arch", flags.arch)));
  const code = arch(file);
  code.emitInt();
  code.emitModule();
}

module.exports = {
  parse,
  compile,
  compileFile,
};
